src/components/Home/Hero.tsx
Task description:
-Кнопка «Дізнатися Більше» має бути перейменована в «Переглянути товари», і вести на сторінку: https://tep-store.vercel.app/goods
Changes:
-Rename button to "Переглянути товари" and modified the href attribute to link to /goods.
=> Update learn more button

src/common/CartNotification.tsx, src/common/FavouriteNotification.tsx
Task Description
- Fix add animation for adding items to cart and favourite using Transition component
=> Feature animated cart favorite

src/components/Footer/Footer.tsx, src/route-urls.ts
Task description:
-Посилання по соц мережам не працюють, оновити.
Changes:
- create Social Media Url object to store links to social media
- use Social Media Url object in footer to get links
=> Fix social media links

.gitignore, src/components/Filters/ProductsFilters.tsx
[THT-48] - bugfix of size filter
=> Fix bug with sizes filter dont working properly

src/app/company/Breadcrumbs.tsx, src/app/company/blog/[slug]/page.tsx, src/app/company/blog/[slug]/pillar/page.tsx, src/app/company/blog/page.tsx, src/components/Company/Blog/Author.tsx, src/components/Filters/CategoriesFilter.tsx, src/components/Footer/Footer.tsx, src/components/Forms/FeedbackForm.tsx, src/components/Goods/Categories.tsx, src/components/Header/Header.tsx, src/components/Info/Feedbacks/FeedbacksFiltersWithCategories.tsx, src/components/Providers.tsx, src/contexts/ArticlesContext.tsx
[THT-44] - The same request to backend send more that one time during rendering the page
=> Bugfix tht 44

src/app/goods/[category]/page.tsx, src/components/Filters/ProductsFilters.tsx, src/contexts/ArticlesContext.tsx, src/contexts/CategoriesContext.tsx
[THT-52] - bugfix filter by category of dynamic filters
=> [THT-52] - bugfix filter by category of dynamic filters

package-lock.json, package.json, src/app/goods/[category]/[product]/page.tsx, src/app/goods/[category]/dao-services.tsx, src/app/goods/[category]/services.tsx, src/components/Filters/ProductsFilters.tsx
[THT-46] Increase number of views
=> [THT-46] Increase number of views

src/app/account/cart/dao-services.tsx, src/app/account/cart/interfaces.tsx, src/app/account/cart/services.tsx, src/app/goods/[category]/[product]/page.tsx, src/app/goods/[category]/page.tsx, src/components/Filters/ProductsFilters.tsx, src/components/Goods/Product/Counter.tsx, src/components/Goods/Product/PaymentDetails.tsx, src/components/User/Cart/Cart.tsx, src/components/User/Cart/CartList.tsx, src/components/User/Cart/CartProductCard.tsx, src/components/User/Cart/TotalPriceBlock.tsx, src/contexts/CategoriesContext.tsx, src/services/productServices.tsx
=> [THT-13] Cart intgration

src/app/account/favourite/dao-services.tsx, src/app/account/favourite/services.tsx, src/app/goods/[category]/page.tsx, src/app/sales/services.tsx, src/components/Goods/Design.tsx, src/components/Goods/LittleGrid.tsx, src/components/Goods/PopularGoods.tsx, src/components/Goods/Product/SimilarGoods.tsx, src/components/Goods/RecommendedGoods.tsx, src/components/Home/ProductCard.tsx, src/components/Home/Recomendations/Recomendations.tsx, src/components/Novelty/Images.tsx, src/components/Novelty/NewGoods.tsx, src/components/User/Favourite/Favourite.tsx, src/components/User/OrderHistory/OrderHistory.tsx, src/data/index.ts
[THT-63] Favorite button integration
=> [THT-63] Favorite button integration

src/app/goods/[category]/[product]/page.tsx, src/app/goods/[category]/page.tsx, src/components/Goods/Product/InfoDisclosure.tsx
=> [THT-70] Add Dimensional grid

src/app/goods/[category]/[product]/page.tsx, src/app/sales/services.tsx, src/components/Goods/Product/SimilarGoods.tsx
[THT-77] Show the same products
=> [THT-77] Show the same products

src/app/goods/[category]/[product]/page.tsx, src/app/goods/[category]/page.tsx, src/components/Goods/Product/PaymentDetails.tsx, src/components/Goods/ProductsList.tsx, src/components/Home/ProductCard.tsx, src/daos/productDAO.tsx
[THT-93] Make working to cart button on the category page
=> [THT-93] Make working to cart button on the category page

src/app/(auth)/email-confirmation/page.tsx, src/app/account/dao-services.tsx, src/app/account/email-confirmation/page.tsx, src/app/account/page.tsx, src/app/account/services.tsx, src/components/Auth/EmailConfirmationForm.tsx, src/components/User/BirthdayForm.tsx, src/components/User/ChangeAvatarForm.tsx, src/components/User/ChangePasswordForm.tsx, src/components/User/UserAccount.tsx, src/components/User/UserAccountForm.tsx, src/components/User/UserSettings.tsx
=> [THT-54] Profile integration

src/app/goods/[category]/[product]/page.tsx, src/app/information-for-buyers/feedbacks/dao-services.tsx, src/app/information-for-buyers/feedbacks/interfaces.tsx, src/app/information-for-buyers/feedbacks/page.tsx, src/app/information-for-buyers/feedbacks/services.tsx, src/components/Forms/FeedbackForm.tsx, src/components/Goods/Product/InfoDisclosure.tsx, src/components/Info/Feedbacks/FeedbackCard.tsx, src/components/Info/Feedbacks/FeedbacksList.tsx
[THT-71] Add feedbacks to product
=> [THT-71] Add feedbacks to product

src/app/company/cooperation-and-partnership/leave-a-request/page.tsx, src/app/company/vacancies/[slug]/leave-a-request/page.tsx, src/app/company/vacancies/dao-services.tsx, src/app/company/vacancies/services.tsx, src/components/Forms/VacancyRequestForm.tsx
[THT-126] Add ability to apply on vacancy
=> [THT-126] Add ability to apply on vacancy

src/app/goods/[category]/defaultValues.tsx, src/app/goods/[category]/page.tsx, src/app/search/dao-services.tsx, src/app/search/page.tsx, src/app/search/services.tsx, src/common/ui/Inputs/AutocompleteInput.tsx, src/components/Filters/ColorCheckboxes/ColorCheckBox.tsx, src/components/Filters/ColorCheckboxes/index.ts, src/components/Filters/SearchFilters.tsx
[THT-89] Integration of onthefly search
=> [THT-89] Integration of onthefly search

src/app/goods/[category]/[product]/page.tsx, src/app/goods/[category]/page.tsx, src/app/search/page.tsx, src/components/Goods/Product/InfoDisclosure.tsx, src/components/Goods/Product/InteriorLook.tsx, src/components/Goods/Product/SimilarGoods.tsx
[THT-117] add images Interior view
=> [THT-117] add images Interior view

src/app/goods/[category]/[product]/page.tsx, src/app/goods/[category]/dao-services.tsx, src/app/goods/[category]/services.tsx, src/app/page.tsx, src/components/Goods/BigGrid.tsx, src/components/Goods/RecommendedGoods.tsx, src/components/User/Cart/Cart.tsx
[THT-130] Make Recomendations component fetch data from a server
=> [THT-130] Make Recomendations component fetch data from a server

src/app/account/favourite/services.tsx, src/app/goods/[category]/[product]/page.tsx, src/app/goods/[category]/dao-services.tsx, src/app/goods/[category]/page.tsx, src/app/goods/[category]/services.tsx, src/app/sales/services.tsx, src/app/search/services.tsx, src/components/Goods/PopularGoods.tsx, src/components/Home/ProductCard.tsx
[THT-97] Add animation of adding to cart
=> [THT-97] Add animation of adding to cart

src/app/goods/[category]/compare/page.tsx, src/app/goods/[category]/page.tsx, src/components/Filters/ProductsFilters.tsx, src/components/Goods/CompareBanner.tsx, src/components/Goods/SalesProductsList.tsx, src/components/Home/ProductCard.tsx, src/contexts/CompareContext.tsx
[THT-150] Make the comparing functionality working
=> [THT-150] Make the comparing functionality working

src/app/company/blog/dao-services.tsx, src/app/company/vacancies/dao-services.tsx, src/app/goods/[category]/[product]/page.tsx, src/app/goods/[category]/services.tsx, src/app/sales/dao-services.tsx, src/app/sales/page.tsx, src/app/sales/services.tsx, src/components/Company/Blog/MoreArticles.tsx, src/components/Goods/Product/PaymentDetails.tsx, src/components/Goods/SalesProductsList.tsx, src/components/Novelty/NewGoods.tsx
=> [THT-147] Bugfix 28.07

src/app/account/dao-services.tsx, src/app/account/page.tsx, src/app/account/services.tsx, src/components/User/UserAccount.tsx, src/components/User/UserAddressForm .tsx, src/components/User/UserSettings.tsx
[THT-142] Add ability to change address, communication and to logout
=> [THT-142] Add ability to change address, communication and to logout

src/app/goods/[category]/dao-services.tsx, src/app/goods/[category]/services.tsx, src/components/Goods/BigGrid.tsx, src/components/Home/Inspiration/Inspiration.tsx, src/utils/helpers.ts
[THT-145] Render inspiration images
=> [THT-145] Render inspiration images

src/app/goods/interior/dao-services.tsx, src/app/goods/interior/services.tsx, src/app/goods/page.tsx, src/common/Tip.tsx, src/components/Goods/Design.tsx, src/components/Goods/Interior/InteriorGoods.tsx, src/components/Goods/Interior/InteriorInspiration.tsx, src/components/Goods/LittleGrid.tsx, src/components/InspirationPage.tsx
[THT-100] Show buy a product when user move your mouse
=> [THT-100] Show buy a product when user move your mouse 

src/components/Home/InfoCard.tsx, src/components/Home/MoreOffers/MoreOffers.tsx
[THT-155] Change images in more offers
=> [THT-155] Change images in more offers

.env.local, package-lock.json, package.json, src/components/Auth/LoginForm.tsx, src/components/Auth/SocialLogin.tsx
[THT-160] Google authorization
=> [THT-160] Google authorization

src/components/Home/Hero.tsx, src/components/Home/HeroCard.tsx
[THT-156] Change main banner to the youtube video on the main page
=> [THT-156] Change main banner to the youtube video on the main page

src/app/goods/[category]/[product]/page.tsx, src/app/goods/[category]/dao-services.tsx, src/app/goods/[category]/page.tsx, src/app/goods/[category]/services.tsx, src/components/Header/HoverMenuCard.tsx, src/components/User/Cart/CartProductCard.tsx, src/components/User/Cart/TotalPriceBlock.tsx, src/daos/productDAO.tsx
[TP2-15] Fix price in cart. If we have the promotion checkbox is true, calculate full price by promo price
[TP2-13] validate in_cart attached to product variant
[TP2-8] Fix in_cart. Attach product from cart to product variant
=> Fix all bugs with cart

src/app/goods/[category]/dao-services.tsx, src/app/goods/[category]/interfaces.ts, src/app/goods/[category]/page.tsx, src/app/goods/[category]/services.tsx, src/components/Filters/ProductsFilters.tsx
[TP2-27] Fix showing of filters
=> [TP2-27] Fix showing of filters

src/app/goods/[category]/[product]/page.tsx, src/app/goods/[category]/page.tsx, src/components/Goods/Product/InfoDisclosure.tsx
[TP2-16] Fix showing of dimensional grid
=> [TP2-16] Fix showing of dimensional grid

src/app/goods/[category]/page.tsx, src/app/search/page.tsx, src/components/Auth/EmailConfirmationForm.tsx, src/components/Forms/FeedbackForm.tsx, src/components/Forms/VacancyRequestForm.tsx, src/components/Header/Header.tsx, src/components/Purchase/OrderData.tsx, src/components/Purchase/PaymentForm.tsx, src/components/User/Cart/Cart.tsx, src/components/User/Cart/CartList.tsx, src/components/User/Cart/TotalPriceBlock.tsx, src/contexts/PostServiceContext.tsx, src/daos/conversionsDAO.ts, src/services/conversionsServices.ts
=> [TP2-33] Add meta pixel

src/app/goods/[category]/page.tsx, src/components/Goods/ProductsList.tsx
[TP2-56] load product with pagination
=> [TP2-56] load product with pagination
